server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      routes:
        - id: report
          uri: lb://report
          predicates:
            - Path=/report/**
        - id: area
          uri: lb://area
          predicates:
            - Path=/area/**
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**