server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      routes:
        - id: report
          uri: http://localhost:12001/report
          predicates:
            - Path=/report/**
        - id: area
          uri: http://localhost:12002/area
          predicates:
            - Path=/area/**
        - id: auth
          uri: http://localhost:12000/auth
          predicates:
            - Path=/auth/**